server:
  port: 8080
  servlet.context-path: /api
  tomcat.threads.max: 5

application:
  name: @project.artifactId@
build:
  version: @project.version@

spring:
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smarthata
    username: smarthata
    password: password

mqtt:
  server-uri: tcp://iot.eclipse.org:1883
  user: user
  password: password

#logging.level.root: DEBUG

bot:
  username: smarthatabot
  token: ${bot.token}
  adminChatId: ${bot.adminChatId}

health:
  devices: /bedroom, /bathroom, /heating, /hum, /light
