server:
  port: 8080
  servlet.context-path: /api
  tomcat.threads.max: 5

spring.profiles.active: dev

application:
  name: '@project.artifactId@'
build:
  version: '@project.version@'

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa.hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smarthata
    username: smarthata
    password: password

mqtt:
  server-uri: tcp://127.0.0.1:1883
  user: user
  password: password

logging.level.root: WARN
logging.level.org.smarthata: INFO

bot:
  enabled: false
  username: smarthatabot
  token: ${bot.token}
  adminChatId: ${bot.adminChatId}

health:
  devices: /bedroom, /heating, /heating/garage, /light, /watering

narodmon:
  enabled: false
  mac: 00:00:00:00:00:00


oauth2.0:
  password: pass

alice:
  url: https://dialogs.yandex.net/api/v1/skills/5a6e8aa0-e300-46dc-bcb7-76d9318855fc
  token: ${token}
